const express=require('express');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const session=require('cookie-session');
const app=express();const db=new Database(path.join(__dirname,'db','koshkakan.sqlite'));db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_id INTEGER,name TEXT,city TEXT,description TEXT,price INTEGER,capacity INTEGER,image TEXT,approved INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES users(id));CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,property_id INTEGER,customer_id INTEGER,checkin TEXT,checkout TEXT,guests INTEGER,total INTEGER,status TEXT DEFAULT 'pending',payment_status TEXT DEFAULT 'unpaid',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(property_id) REFERENCES properties(id),FOREIGN KEY(customer_id) REFERENCES users(id));CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,booking_id INTEGER,amount INTEGER,method TEXT,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(booking_id) REFERENCES bookings(id));`);
const adminEmail=process.env.ADMIN_EMAIL||'admin@koshkakan.local';const adminPassword=process.env.ADMIN_PASSWORD||'Admin123!';const admin=db.prepare('SELECT id FROM users WHERE email=?').get(adminEmail);if(!admin)db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run('Admin',adminEmail,bcrypt.hashSync(adminPassword,10),'admin');
app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));app.use(session({name:'koshkakan',keys:[process.env.SESSION_SECRET||'dev-only-change-me'],httpOnly:true,sameSite:'lax',maxAge:7*86400000}));app.use(express.static(path.join(__dirname,'public')));
function user(req,res,next){req.me=req.session.userId?db.prepare('SELECT id,name,email,role FROM users WHERE id=?').get(req.session.userId):null;next()}app.use(user);function auth(req,res,next){if(!req.me)return res.status(401).json({error:'login_required'});next()}function role(r){return(req,res,next)=>{if(!req.me||req.me.role!==r)return res.status(403).json({error:'forbidden'});next()}}
app.get('/api/me',(req,res)=>res.json(req.me||null));
app.post('/api/register',(req,res)=>{try{const {name,email,password,role:requestedRole}=req.body;if(!name||!email||!password)return res.status(400).json({error:'هەموو خانەکان پڕبکەرەوە'});const safeRole=requestedRole==='owner'?'owner':'customer';const info=db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run(name,email,bcrypt.hashSync(password,10),safeRole);req.session.userId=info.lastInsertRowid;res.json({ok:true})}catch(e){res.status(400).json({error:'ئەم ئیمەیڵە پێشتر بەکارهاتووە'})}});
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:'ئیمەیڵ یان وشەی نهێنی هەڵەیە'});req.session.userId=u.id;res.json({ok:true})});app.post('/api/logout',(req,res)=>{req.session=null;res.json({ok:true})});
app.get('/api/properties',(req,res)=>res.json(db.prepare("SELECT p.*,u.name owner FROM properties p JOIN users u ON u.id=p.owner_id WHERE p.approved=1 ORDER BY p.id DESC").all()));
app.post('/api/properties',auth,role('owner'),(req,res)=>{const {name,city,description,price,capacity,image}=req.body;const r=db.prepare('INSERT INTO properties(owner_id,name,city,description,price,capacity,image) VALUES(?,?,?,?,?,?,?)').run(req.me.id,name,city,description,Number(price),Number(capacity),image||'');res.json({id:r.lastInsertRowid})});
app.get('/api/owner/properties',auth,role('owner'),(req,res)=>res.json(db.prepare('SELECT * FROM properties WHERE owner_id=? ORDER BY id DESC').all(req.me.id)));
app.post('/api/bookings',auth,(req,res)=>{const {property_id,checkin,checkout,guests}=req.body;const p=db.prepare('SELECT * FROM properties WHERE id=? AND approved=1').get(property_id);if(!p)return res.status(404).json({error:'کۆشک نەدۆزرایەوە'});if(new Date(checkout)<=new Date(checkin))return res.status(400).json({error:'بەروارەکان هەڵەن'});const days=Math.max(1,Math.ceil((new Date(checkout)-new Date(checkin))/86400000));const total=days*p.price;const r=db.prepare('INSERT INTO bookings(property_id,customer_id,checkin,checkout,guests,total) VALUES(?,?,?,?,?,?)').run(p.id,req.me.id,checkin,checkout,Number(guests),total);res.json({id:r.lastInsertRowid,total})});
app.get('/api/bookings',auth,(req,res)=>{const q=req.me.role==='owner'?`SELECT b.*,p.name property,u.name customer FROM bookings b JOIN properties p ON p.id=b.property_id JOIN users u ON u.id=b.customer_id WHERE p.owner_id=? ORDER BY b.id DESC`:`SELECT b.*,p.name property FROM bookings b JOIN properties p ON p.id=b.property_id WHERE b.customer_id=? ORDER BY b.id DESC`;res.json(db.prepare(q).all(req.me.id))});
app.patch('/api/bookings/:id',auth,(req,res)=>{const b=db.prepare('SELECT b.*,p.owner_id FROM bookings b JOIN properties p ON p.id=b.property_id WHERE b.id=?').get(req.params.id);if(!b)return res.sendStatus(404);if(req.me.role==='owner'&&b.owner_id!==req.me.id)return res.sendStatus(403);if(req.me.role==='customer'&&b.customer_id!==req.me.id)return res.sendStatus(403);db.prepare('UPDATE bookings SET status=?,payment_status=? WHERE id=?').run(req.body.status||b.status,req.body.payment_status||b.payment_status,b.id);res.json({ok:true})});
app.post('/api/payments',auth,(req,res)=>{const b=db.prepare('SELECT * FROM bookings WHERE id=? AND customer_id=?').get(req.body.booking_id,req.me.id);if(!b)return res.sendStatus(404);const r=db.prepare('INSERT INTO payments(booking_id,amount,method,status) VALUES(?,?,?,?)').run(b.id,b.total,req.body.method||'manual','pending');res.json({id:r.lastInsertRowid,message:'داواکاری پارەدان تۆمارکرا. بۆ پارەدانی ئۆنلاین Gateway زیاد دەکرێت.'})});
app.get('/api/admin/stats',auth,role('admin'),(req,res)=>res.json({users:db.prepare('SELECT COUNT(*) n FROM users').get().n,properties:db.prepare('SELECT COUNT(*) n FROM properties').get().n,pending:db.prepare('SELECT COUNT(*) n FROM properties WHERE approved=0').get().n,bookings:db.prepare('SELECT COUNT(*) n FROM bookings').get().n,revenue:db.prepare("SELECT COALESCE(SUM(total),0) n FROM bookings WHERE status='confirmed'").get().n}));
app.get('/api/admin/properties',auth,role('admin'),(req,res)=>res.json(db.prepare('SELECT p.*,u.name owner,u.email FROM properties p JOIN users u ON u.id=p.owner_id ORDER BY p.id DESC').all()));app.patch('/api/admin/properties/:id',auth,role('admin'),(req,res)=>{db.prepare('UPDATE properties SET approved=? WHERE id=?').run(req.body.approved?1:0,req.params.id);res.json({ok:true})});
app.get('/api/admin/users',auth,role('admin'),(req,res)=>res.json(db.prepare('SELECT id,name,email,role,created_at FROM users ORDER BY id DESC').all()));app.patch('/api/admin/users/:id/role',auth,role('admin'),(req,res)=>{const allowed=['customer','owner'];if(!allowed.includes(req.body.role))return res.status(400).json({error:'role_invalid'});db.prepare('UPDATE users SET role=? WHERE id=?').run(req.body.role,req.params.id);res.json({ok:true})});app.get('/api/health',(req,res)=>res.json({ok:true,service:'koshkakan'}));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(process.env.PORT||3000,()=>console.log('Koshkakan running'));
